### ISSUE TITLE
Can't Load Components

### ISSUE THREAD

**Issue by MonteKrysto** [aichbauer/styled-bootstrap-components#16]
I have installed `styled-components` and `styled-bootstrap-components`.  

This is my component:
```
import { Container, Button, Nav, Navbar, NavbarLink } from "styled-bootstrap-components";

const AllNav = props => (
  <Container fluid>
    <Container fluid>
      <Navbar expandSm light>
        <Nav start>
          <NavbarLink light brand href="#">
            BRAND
          </NavbarLink>
          <Button
            light
            outline
            toggleCollapse
            expandSm
            onClick={() => console.log("close")}
          >
            <span>&#9776;</span>
          </Button>
        </Nav>
        <Nav start collapse expandSm hidden={hidden}>
          <Link light active href="#">
            <a>Active</a>
          </Link>
          <Link light href="#">
            <a>Link</a>
          </Link>
          <Link light href="#">
            <a>Link</a>
          </Link>
          <Link light disabled href="#">
            <a>Disabled</a>
          </Link>
        </Nav>
      </Navbar>
    </Container>
  </Container>
);

export default AllNav;
```

When accessing the app after building I get:

```
node_modules/styled-config/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { theme } from './theme';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xxx/Code/xxx/frontend/node_modules/styled-alert-component/lib/components/Alert.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
/Users/xxx/Code/xxx/frontend/node_modules/styled-config/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { theme } from './theme';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xxx/Code/xxx/frontend/node_modules/styled-alert-component/lib/components/Alert.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
/Users/xxx/Code/xxx/frontend/node_modules/styled-config/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { theme } from './theme';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xxx/Code/xxx/frontend/node_modules/styled-alert-component/lib/components/Alert.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
/Users/xxx/Code/xxx/frontend/node_modules/styled-config/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { import { theme } from './theme';
                                                                     ^

SyntaxError: Unexpected token {
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:684:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/xxx/Code/xxx/frontend/node_modules/styled-alert-component/lib/components/Alert.js:10:21)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)

```

Is there another step I am missing?

**Comment by aichbauer** [comment]
Hey, thank you for your issue.

Could you create a repo or a code-sandbox where this issue also happens? Which versions of styled-components and styled-bootstrap-components are you using?

I created a code sandbox example to show you how it is working.

[![Edit 54zpqpll1p](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/54zpqpll1p)

**Comment by aichbauer** [comment]
I see what the problem is.

It should work now with v3.0.1

Here is a working example.

[![Edit donate-to-donate-frontend](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/v3q98n8w0)

If you are using a themeprovider, you need to inject the theme of `styled-bootstrap-components`.

**Comment by MonteKrysto** [comment]
Thank you for the fix, that worked!
